/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormRouteRouteImport } from './routes/form/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormIndexRouteImport } from './routes/form/index'
import { Route as FormStepTwoRouteImport } from './routes/form/step-two'
import { Route as FormStepOneRouteImport } from './routes/form/step-one'
import { Route as FormConfirmRouteImport } from './routes/form/confirm'

const FormRouteRoute = FormRouteRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIndexRoute = FormIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormStepTwoRoute = FormStepTwoRouteImport.update({
  id: '/step-two',
  path: '/step-two',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormStepOneRoute = FormStepOneRouteImport.update({
  id: '/step-one',
  path: '/step-one',
  getParentRoute: () => FormRouteRoute,
} as any)
const FormConfirmRoute = FormConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => FormRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRouteRouteWithChildren
  '/form/confirm': typeof FormConfirmRoute
  '/form/step-one': typeof FormStepOneRoute
  '/form/step-two': typeof FormStepTwoRoute
  '/form/': typeof FormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/confirm': typeof FormConfirmRoute
  '/form/step-one': typeof FormStepOneRoute
  '/form/step-two': typeof FormStepTwoRoute
  '/form': typeof FormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form': typeof FormRouteRouteWithChildren
  '/form/confirm': typeof FormConfirmRoute
  '/form/step-one': typeof FormStepOneRoute
  '/form/step-two': typeof FormStepTwoRoute
  '/form/': typeof FormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form'
    | '/form/confirm'
    | '/form/step-one'
    | '/form/step-two'
    | '/form/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/confirm' | '/form/step-one' | '/form/step-two' | '/form'
  id:
    | '__root__'
    | '/'
    | '/form'
    | '/form/confirm'
    | '/form/step-one'
    | '/form/step-two'
    | '/form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRouteRoute: typeof FormRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/': {
      id: '/form/'
      path: '/'
      fullPath: '/form/'
      preLoaderRoute: typeof FormIndexRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/form/step-two': {
      id: '/form/step-two'
      path: '/step-two'
      fullPath: '/form/step-two'
      preLoaderRoute: typeof FormStepTwoRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/form/step-one': {
      id: '/form/step-one'
      path: '/step-one'
      fullPath: '/form/step-one'
      preLoaderRoute: typeof FormStepOneRouteImport
      parentRoute: typeof FormRouteRoute
    }
    '/form/confirm': {
      id: '/form/confirm'
      path: '/confirm'
      fullPath: '/form/confirm'
      preLoaderRoute: typeof FormConfirmRouteImport
      parentRoute: typeof FormRouteRoute
    }
  }
}

interface FormRouteRouteChildren {
  FormConfirmRoute: typeof FormConfirmRoute
  FormStepOneRoute: typeof FormStepOneRoute
  FormStepTwoRoute: typeof FormStepTwoRoute
  FormIndexRoute: typeof FormIndexRoute
}

const FormRouteRouteChildren: FormRouteRouteChildren = {
  FormConfirmRoute: FormConfirmRoute,
  FormStepOneRoute: FormStepOneRoute,
  FormStepTwoRoute: FormStepTwoRoute,
  FormIndexRoute: FormIndexRoute,
}

const FormRouteRouteWithChildren = FormRouteRoute._addFileChildren(
  FormRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRouteRoute: FormRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
